install.packages("ggplot2",repos = "http://cran.us.r-project.org")
install.packages("plyr",repos = "http://cran.us.r-project.org")
install.packages("effsize",repos = "http://cran.us.r-project.org")
install.packages("randomForest",repos = "http://cran.us.r-project.org")
install.packages("doParallel",repos = "http://cran.us.r-project.org")
install.packages("gridExtra",repos = "http://cran.us.r-project.org")
install.packages("grid",repos = "http://cran.us.r-project.org")
install.packages("Hmisc",repos = "http://cran.us.r-project.org")
install.packages("devtools",repos = "http://cran.us.r-project.org")
devtools::install_github("awsm-research/Rnalytica")
